import { Repository, Worker, HealdecLogEntry, LogEntry } from './types'

export function generateSeedData() {
  const repositories: Repository[] = [
    {
      id: 'repo-1',
      provider: 'github',
      owner: 'algorand',
      name: 'go-algorand',
      defaultBranch: 'master',
      lastIndexedAt: new Date(Date.now() - 3600000).toISOString(),
      healthScore: 92,
      activityScore: 88,
      governanceScore: 95,
      claimsCount: 12,
      frameworks: ['Go', 'Docker', 'Kubernetes'],
    },
    {
      id: 'repo-2',
      provider: 'github',
      owner: 'algorand',
      name: 'js-algorand-sdk',
      defaultBranch: 'develop',
      lastIndexedAt: new Date(Date.now() - 7200000).toISOString(),
      healthScore: 87,
      activityScore: 91,
      governanceScore: 85,
      claimsCount: 8,
      frameworks: ['JavaScript', 'TypeScript', 'Node.js'],
    },
    {
      id: 'repo-3',
      provider: 'github',
      owner: 'algorand',
      name: 'py-algorand-sdk',
      defaultBranch: 'master',
      lastIndexedAt: new Date(Date.now() - 1800000).toISOString(),
      healthScore: 90,
      activityScore: 84,
      governanceScore: 88,
      claimsCount: 6,
      frameworks: ['Python', 'Poetry'],
    },
    {
      id: 'repo-4',
      provider: 'github',
      owner: 'algorand',
      name: 'indexer',
      defaultBranch: 'develop',
      lastIndexedAt: new Date(Date.now() - 5400000).toISOString(),
      healthScore: 85,
      activityScore: 78,
      governanceScore: 82,
      claimsCount: 4,
      frameworks: ['Go', 'PostgreSQL', 'Docker'],
    },
    {
      id: 'repo-5',
      provider: 'github',
      owner: 'algorand',
      name: 'sandbox',
      defaultBranch: 'master',
      lastIndexedAt: new Date(Date.now() - 10800000).toISOString(),
      healthScore: 94,
      activityScore: 96,
      governanceScore: 92,
      claimsCount: 15,
      frameworks: ['Docker', 'Shell', 'Python'],
    },
  ]

  const workers: Worker[] = [
    {
      id: 'worker-1',
      type: 'index',
      status: 'healthy',
      lastRun: new Date(Date.now() - 300000).toISOString(),
      jobsCompleted: 2847,
      jobsFailed: 12,
      avgDuration: 2340,
      queueSize: 3,
    },
    {
      id: 'worker-2',
      type: 'identity',
      status: 'healthy',
      lastRun: new Date(Date.now() - 180000).toISOString(),
      jobsCompleted: 1923,
      jobsFailed: 8,
      avgDuration: 1450,
      queueSize: 1,
    },
    {
      id: 'worker-3',
      type: 'score',
      status: 'healthy',
      lastRun: new Date(Date.now() - 420000).toISOString(),
      jobsCompleted: 3421,
      jobsFailed: 5,
      avgDuration: 890,
      queueSize: 2,
    },
    {
      id: 'worker-4',
      type: 'ingest',
      status: 'healthy',
      lastRun: new Date(Date.now() - 60000).toISOString(),
      jobsCompleted: 8234,
      jobsFailed: 34,
      avgDuration: 560,
      queueSize: 12,
    },
    {
      id: 'worker-5',
      type: 'sync',
      status: 'degraded',
      lastRun: new Date(Date.now() - 900000).toISOString(),
      jobsCompleted: 1567,
      jobsFailed: 23,
      avgDuration: 3200,
      queueSize: 8,
    },
    {
      id: 'worker-6',
      type: 'gc',
      status: 'healthy',
      lastRun: new Date(Date.now() - 3600000).toISOString(),
      jobsCompleted: 456,
      jobsFailed: 2,
      avgDuration: 5600,
      queueSize: 0,
    },
    {
      id: 'worker-7',
      type: 'alert',
      status: 'healthy',
      lastRun: new Date(Date.now() - 240000).toISOString(),
      jobsCompleted: 892,
      jobsFailed: 7,
      avgDuration: 340,
      queueSize: 1,
    },
    {
      id: 'worker-8',
      type: 'export',
      status: 'healthy',
      lastRun: new Date(Date.now() - 7200000).toISOString(),
      jobsCompleted: 234,
      jobsFailed: 1,
      avgDuration: 8900,
      queueSize: 0,
    },
    {
      id: 'worker-9',
      type: 'audit',
      status: 'healthy',
      lastRun: new Date(Date.now() - 1800000).toISOString(),
      jobsCompleted: 678,
      jobsFailed: 15,
      avgDuration: 4200,
      queueSize: 2,
    },
    {
      id: 'worker-10',
      type: 'repair',
      status: 'healthy',
      lastRun: new Date(Date.now() - 5400000).toISOString(),
      jobsCompleted: 145,
      jobsFailed: 8,
      avgDuration: 6700,
      queueSize: 1,
    },
    {
      id: 'worker-11',
      type: 'backfill',
      status: 'healthy',
      lastRun: new Date(Date.now() - 10800000).toISOString(),
      jobsCompleted: 89,
      jobsFailed: 3,
      avgDuration: 15600,
      queueSize: 0,
    },
    {
      id: 'worker-12',
      type: 'maintenance',
      status: 'healthy',
      lastRun: new Date(Date.now() - 14400000).toISOString(),
      jobsCompleted: 67,
      jobsFailed: 1,
      avgDuration: 12300,
      queueSize: 0,
    },
  ]

  const healdecLogs: HealdecLogEntry[] = [
    {
      id: 'heal-1',
      timestamp: new Date(Date.now() - 3600000).toISOString(),
      workerType: 'sync',
      action: 'retry',
      reason: 'Database connection timeout, retrying with backoff',
      jobId: 'job-sync-1234',
      metadata: { attempt: 2, backoffMs: 2000 },
    },
    {
      id: 'heal-2',
      timestamp: new Date(Date.now() - 7200000).toISOString(),
      workerType: 'index',
      action: 'repair_triggered',
      reason: 'Stale index detected, triggering repair worker',
      jobId: 'job-index-5678',
      metadata: { recordsStale: 45 },
    },
    {
      id: 'heal-3',
      timestamp: new Date(Date.now() - 10800000).toISOString(),
      workerType: 'ingest',
      action: 'reroute',
      reason: 'Primary ingestion endpoint down, rerouting to backup',
      jobId: 'job-ingest-9012',
      metadata: { backupEndpoint: 'https://backup.api.example.com' },
    },
  ]

  const logs: LogEntry[] = [
    {
      id: 'log-1',
      timestamp: new Date(Date.now() - 300000).toISOString(),
      level: 'info',
      workerType: 'index',
      message: 'Successfully indexed repository: algorand/go-algorand',
      context: { repoId: 'repo-1', commitCount: 234 },
    },
    {
      id: 'log-2',
      timestamp: new Date(Date.now() - 600000).toISOString(),
      level: 'warn',
      workerType: 'sync',
      message: 'Sync operation taking longer than expected',
      context: { duration: 8900, threshold: 5000 },
    },
    {
      id: 'log-3',
      timestamp: new Date(Date.now() - 900000).toISOString(),
      level: 'error',
      workerType: 'audit',
      message: 'Governance threshold breach detected',
      context: { repoId: 'repo-4', score: 82, threshold: 85 },
    },
    {
      id: 'log-4',
      timestamp: new Date(Date.now() - 1200000).toISOString(),
      level: 'info',
      workerType: 'identity',
      message: 'Identity claim verified for user alice-dev',
      context: { claimId: 'claim-123', handle: 'alice-dev' },
    },
  ]

  return { repositories, workers, healdecLogs, logs }
}
